# config/config.yaml

data:
  ticker: "GC=F"
  interval: "1h"
  period: "15d"

strategy:
  tp_mult: 2.0
  sl_mult: 1.0

training:
  train_size_ratio: 0.75
  test_size_ratio: 0.05
  model_name: "XGBoost_Trading_Model"
  model_path: "models/XGBoost_Trading_Model.pkl"
