# config/config.yaml

data:
  ticker: "GC=F"
  interval: "5m"
  period: "7d"

strategy:
  tp_mult: 2.0
  sl_mult: 1.0

training:
  n_splits: 5
  model_name: "XGBoost_Trading_Model"
  model_path: "models/XGBoost_Trading_Model.pkl"
