# .github/workflows/ci-pipeline.yml

name: CI/CD Pipeline Trading

# à chaque push sur la branche main
on:
  push:
    branches: [main]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      packages: write 

   steps:
    - name: Vérification du code
      uses: actions/checkout@v4

    - name: Configuer Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache des dépendances python
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip- # LIGNE 14 CORRIGÉE (syntaxe YAML)

    - name: Installer les dépendances y compris pytest
      run: pip install -r requirements.txt pytest

    - name: Exécuter les tests unitaires avec pytest
      run: pytest

    - name: Configuration des identifiants Docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Définir les métadonnées de l'image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha,prefix=,suffix=-${{ github.sha }},format=long
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          
    - name: Construire et pousser l'image Docker
      uses: docker/build-push-action@v5
      with:
        context: . # Corrigé : Utilise le répertoire racine pour le contexte Docker
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
